# Generated by Django 3.2.20 on 2023-11-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20231028_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='avatar_str',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
