# Generated by Django 3.2.20 on 2023-11-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_manager_avatar_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='avatar_str',
            field=models.TextField(blank=True, null=True),
        ),
    ]
