# Generated by Django 3.2.20 on 2023-11-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_manager_avatar_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_str',
            field=models.TextField(blank=True, null=True),
        ),
    ]
