# Generated by Django 3.2.20 on 2023-11-04 04:09

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_team_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.TextField()),
                ('timeStart', models.DateTimeField(default=datetime.datetime(2023, 11, 4, 11, 9, 49, 535191))),
                ('timeEnd', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oop_team', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('timeStart', models.DateTimeField(default=datetime.datetime(2023, 11, 4, 11, 9, 49, 535500))),
                ('timeEnd', models.DateTimeField(blank=True, null=True)),
                ('stadium', models.CharField(blank=True, max_length=500, null=True)),
                ('inningERA', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.TextField()),
                ('timeStart', models.DateField()),
                ('timeEnd', models.DateField()),
                ('achieve', models.IntegerField(blank=True, choices=[(1, 'Champion'), (2, 'Runner-up'), (3, 'Third place'), (0, 'No achivement')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstPos', models.IntegerField(blank=True, choices=[(1, 'Picther'), (2, 'Catcher'), (3, 'First baseman'), (4, 'Second baseman'), (5, 'Third baseman'), (6, 'Shortstop'), (7, 'Left fielder'), (8, 'Center fielder'), (9, 'Right fielder'), (0, 'Desinated Hitter'), (-1, 'Not position')], default=-1)),
                ('secondPos', models.IntegerField(blank=True, choices=[(1, 'Picther'), (2, 'Catcher'), (3, 'First baseman'), (4, 'Second baseman'), (5, 'Third baseman'), (6, 'Shortstop'), (7, 'Left fielder'), (8, 'Center fielder'), (9, 'Right fielder'), (0, 'Desinated Hitter'), (-1, 'Not position')], default=-1)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('joinDate', models.DateField(blank=True, null=True)),
                ('homeTown', models.TextField(blank=True, null=True)),
                ('jerseyNumber', models.IntegerField(blank=True, default=-1, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=11, null=True)),
                ('avatar', models.ImageField(blank=True, default='avatars/avatar.png', null=True, upload_to='avatars/')),
                ('avatar_str', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Attend'), (0, 'Not attend'), (2, 'Pending')], default=2)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='PitcherGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitchBall', models.IntegerField(blank=True, default=0, null=True)),
                ('pictchStrike', models.IntegerField(blank=True, default=0, null=True)),
                ('totalBatterFaced', models.IntegerField(blank=0, default=0, null=True)),
                ('totalInGameOut', models.IntegerField(blank=True, default=0, null=True)),
                ('oppHit', models.IntegerField(blank=True, default=0, null=True)),
                ('oppRun', models.IntegerField(blank=True, default=0, null=True)),
                ('earnedRun', models.IntegerField(blank=True, default=0, null=True)),
                ('oppBaseOnBall', models.IntegerField(blank=True, default=0, null=True)),
                ('strikeout', models.IntegerField(blank=True, default=0, null=True)),
                ('hitBatter', models.IntegerField(blank=True, default=0, null=True)),
                ('balk', models.IntegerField(blank=True, default=0, null=True)),
                ('wildPitch', models.IntegerField(blank=True, default=0, null=True)),
                ('oppHomeRun', models.IntegerField(blank=True, default=0, null=True)),
                ('oppSacrificeHit', models.IntegerField(blank=True, default=0, null=True)),
                ('oppSacrificeFly', models.IntegerField(blank=True, default=0, null=True)),
                ('catcherInterference', models.IntegerField(blank=True, default=0, null=True)),
                ('firstPitchStrike', models.IntegerField(blank=True, default=0, null=True)),
                ('pickOff', models.IntegerField(blank=True, default=0, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.league'),
        ),
        migrations.CreateModel(
            name='FielderGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentPos', models.IntegerField(blank=True, choices=[(1, 'Picther'), (2, 'Catcher'), (3, 'First baseman'), (4, 'Second baseman'), (5, 'Third baseman'), (6, 'Shortstop'), (7, 'Left fielder'), (8, 'Center fielder'), (9, 'Right fielder'), (0, 'Desinated Hitter'), (-1, 'Not position')], default=-1)),
                ('playedPos', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(1, 'Picther'), (2, 'Catcher'), (3, 'First baseman'), (4, 'Second baseman'), (5, 'Third baseman'), (6, 'Shortstop'), (7, 'Left fielder'), (8, 'Center fielder'), (9, 'Right fielder'), (0, 'Desinated Hitter'), (-1, 'Not position')], default=-1), size=None)),
                ('totalInGameOut', models.IntegerField(blank=True, default=0, null=True)),
                ('putOut', models.IntegerField(blank=True, default=0, null=True)),
                ('assist', models.IntegerField(blank=True, default=0, null=True)),
                ('error', models.IntegerField(blank=True, default=0, null=True)),
                ('outfieldAssist', models.IntegerField(blank=True, default=0, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='BatterGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateApperance', models.IntegerField(blank=True, default=0, null=True)),
                ('runBattedIn', models.IntegerField(blank=True, default=0, null=True)),
                ('single', models.IntegerField(blank=True, default=0, null=True)),
                ('double', models.IntegerField(blank=True, default=0, null=True)),
                ('triple', models.IntegerField(blank=True, default=0, null=True)),
                ('homeRun', models.IntegerField(blank=True, default=0, null=True)),
                ('baseOnBall', models.IntegerField(blank=True, default=0, null=True)),
                ('intentionalBB', models.IntegerField(blank=True, default=0, null=True)),
                ('hitByPitch', models.IntegerField(blank=True, default=0, null=True)),
                ('strikeOut', models.IntegerField(blank=True, default=0, null=True)),
                ('fielderChoice', models.IntegerField(blank=True, default=0, null=True)),
                ('sacrificeFly', models.IntegerField(blank=True, default=0, null=True)),
                ('sacrificeHit', models.IntegerField(blank=True, default=0, null=True)),
                ('stolenBase', models.IntegerField(blank=True, default=0, null=True)),
                ('leftOnBase', models.IntegerField(blank=True, default=0, null=True)),
                ('doublePlay', models.IntegerField(blank=True, default=0, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
        ),
    ]
