# Generated by Django 3.2.20 on 2023-11-04 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20231104_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='firstName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='player',
            name='lastName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 14, 42, 20, 450881)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 14, 42, 20, 451111)),
        ),
    ]
