# Generated by Django 3.2.20 on 2023-11-09 10:58

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20231104_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bat_hand',
            field=models.CharField(blank=True, choices=[('S', 'Switch'), ('L', 'Left'), ('R', 'Right')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='throw_hand',
            field=models.CharField(blank=True, choices=[('S', 'Switch'), ('L', 'Left'), ('R', 'Right')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 17, 58, 9, 378182)),
        ),
        migrations.AlterField(
            model_name='fieldergame',
            name='currentPos',
            field=models.IntegerField(blank=True, choices=[(1, 'Picther'), (2, 'Catcher'), (3, 'First baseman'), (4, 'Second baseman'), (5, 'Third baseman'), (6, 'Shortstop'), (7, 'Outfielder'), (0, 'Desinated Hitter'), (-1, 'Not position')], default=-1),
        ),
        migrations.AlterField(
            model_name='fieldergame',
            name='playedPos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(1, 'Picther'), (2, 'Catcher'), (3, 'First baseman'), (4, 'Second baseman'), (5, 'Third baseman'), (6, 'Shortstop'), (7, 'Outfielder'), (0, 'Desinated Hitter'), (-1, 'Not position')], default=-1), size=None),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 17, 58, 9, 379187)),
        ),
        migrations.AlterField(
            model_name='player',
            name='firstPos',
            field=models.IntegerField(blank=True, choices=[(1, 'Picther'), (2, 'Catcher'), (3, 'First baseman'), (4, 'Second baseman'), (5, 'Third baseman'), (6, 'Shortstop'), (7, 'Outfielder'), (0, 'Desinated Hitter'), (-1, 'Not position')], default=-1),
        ),
        migrations.AlterField(
            model_name='player',
            name='secondPos',
            field=models.IntegerField(blank=True, choices=[(1, 'Picther'), (2, 'Catcher'), (3, 'First baseman'), (4, 'Second baseman'), (5, 'Third baseman'), (6, 'Shortstop'), (7, 'Outfielder'), (0, 'Desinated Hitter'), (-1, 'Not position')], default=-1),
        ),
    ]
