# Generated by Django 3.2.20 on 2023-11-13 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20231113_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='bat_hand',
            new_name='batHand',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='throw_hand',
            new_name='throwHand',
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 12, 19, 9, 406973)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 12, 19, 9, 406973)),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='shortName',
            field=models.CharField(db_index=True, max_length=4, unique=True),
        ),
    ]
