# Generated by Django 3.2.20 on 2023-11-14 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20231113_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 14, 15, 25, 3, 952794)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 14, 15, 25, 3, 955793)),
        ),
        migrations.AlterField(
            model_name='player',
            name='firstPos',
            field=models.IntegerField(blank=True, choices=[(1, 'Picther'), (2, 'Catcher'), (3, 'First baseman'), (4, 'Second baseman'), (5, 'Third baseman'), (6, 'Shortstop'), (7, 'Outfielder'), (0, 'Desinated Hitter'), (-1, 'Not position')], default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='secondPos',
            field=models.IntegerField(blank=True, choices=[(1, 'Picther'), (2, 'Catcher'), (3, 'First baseman'), (4, 'Second baseman'), (5, 'Third baseman'), (6, 'Shortstop'), (7, 'Outfielder'), (0, 'Desinated Hitter'), (-1, 'Not position')], default=-1, null=True),
        ),
    ]
