# Generated by Django 3.2.20 on 2023-11-15 15:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20231114_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.team'),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 22, 3, 59, 360513)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 22, 3, 59, 360513)),
        ),
    ]
