# Generated by Django 3.2.20 on 2023-11-15 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20231115_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='oop_team',
            new_name='oppTeam',
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 22, 9, 29, 229232)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 22, 9, 29, 229232)),
        ),
    ]
