# Generated by Django 3.2.20 on 2023-11-16 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20231115_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='battergame',
            name='run',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 9, 24, 15, 759412)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 9, 24, 15, 759412)),
        ),
    ]
