# Generated by Django 3.2.20 on 2023-11-16 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20231116_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='battergame',
            name='onBaseByError',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 9, 38, 48, 443192)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 9, 38, 48, 443192)),
        ),
    ]
