# Generated by Django 3.2.20 on 2023-11-18 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20231116_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='joinDate',
            new_name='birthDate',
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 18, 10, 54, 3, 341474)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 18, 10, 54, 3, 341474)),
        ),
    ]
