# Generated by Django 3.2.20 on 2023-11-25 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20231118_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.IntegerField(blank=True, choices=[(-1, 'Upcoming'), (0, 'In progress'), (1, 'Completed')], default=-1),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.IntegerField(blank=True, choices=[(-1, 'Upcoming'), (0, 'In progress'), (1, 'Completed')], default=-1),
        ),
        migrations.AddField(
            model_name='league',
            name='status',
            field=models.IntegerField(blank=True, choices=[(-1, 'Upcoming'), (0, 'In progress'), (1, 'Completed')], default=-1),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 10, 6, 45, 33666)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 10, 6, 45, 33666)),
        ),
    ]
