# Generated by Django 3.2.20 on 2023-12-02 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20231125_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 23, 49, 31, 921888)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 23, 49, 31, 921888)),
        ),
    ]
