# Generated by Django 3.2.20 on 2023-12-02 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20231202_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='oppTeamShort',
            field=models.CharField(default='TEAM', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 0, 5, 2, 897475)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 0, 5, 2, 897475)),
        ),
    ]
