# Generated by Django 3.2.20 on 2023-12-18 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20231203_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 10, 8, 28, 730608)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 10, 8, 28, 747389)),
        ),
        migrations.AlterField(
            model_name='league',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='timeEnd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='timeStart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
