# Generated by Django 3.2.20 on 2024-01-09 18:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20231218_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='battergame',
            name='battingOrder',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 1, 34, 55, 581154)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 1, 34, 55, 581154)),
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, max_length=500, null=True)),
                ('timeStart', models.DateTimeField(default=datetime.datetime(2024, 1, 10, 1, 34, 55, 581154))),
                ('timeEnd', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(-1, 'Upcoming'), (0, 'In progress'), (1, 'Completed')], default=-1)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Attend'), (0, 'Not attend'), (2, 'Pending')], default=2)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.practice')),
            ],
        ),
    ]
