# Generated by Django 3.2.20 on 2024-01-12 09:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20240110_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamFund',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 16, 7, 59, 369823)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 16, 7, 59, 369823)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 16, 7, 59, 369823)),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Present'), (2, 'League prize'), (3, 'Monthly fund'), (4, 'Other add'), (-1, 'Buy item'), (-2, 'Held event'), (-3, 'Give present'), (-4, 'Other minus')], default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2024, 1, 12, 16, 7, 59, 369823))),
                ('status', models.IntegerField(blank=True, choices=[(-1, 'Upcoming'), (0, 'In progress'), (1, 'Completed')], default=-1)),
                ('price', models.BigIntegerField()),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TimeField(blank=True, null=True)),
                ('price', models.BigIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
    ]
