# Generated by Django 3.2.20 on 2024-01-13 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20240113_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offensepitchbypitch',
            name='batter',
        ),
        migrations.RemoveField(
            model_name='offensepitchbypitch',
            name='game',
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 15, 34, 34, 703897)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 15, 34, 34, 703897)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 15, 34, 34, 703897)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 15, 34, 34, 703897)),
        ),
        migrations.DeleteModel(
            name='DefensePitchByPitch',
        ),
        migrations.DeleteModel(
            name='OffensePitchByPitch',
        ),
    ]
