# Generated by Django 3.2.20 on 2024-01-13 08:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20240113_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 15, 35, 0, 581670)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 15, 35, 0, 581670)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 15, 35, 0, 581670)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 15, 35, 0, 581670)),
        ),
        migrations.CreateModel(
            name='OffensePitchByPitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_count', models.IntegerField()),
                ('ball_count', models.IntegerField()),
                ('strike_count', models.IntegerField()),
                ('outcome', models.IntegerField(blank=True, choices=[(1, 'Strikeout Looking'), (2, 'Strikeout Swinging'), (3, 'Groundout'), (4, 'Pop/Flyout'), (5, 'Sacrifice Fly'), (6, 'Sacrifice Bunt'), (7, 'Infield Fly'), (8, 'Dropped 3rd strike'), (9, 'Double Play'), (10, 'Triple Play'), (11, 'Walk'), (12, 'Intentional Walk'), (13, 'Single'), (14, 'Double'), (15, 'Triple'), (16, 'Homerun'), (17, 'Inside park Homerun'), (18, 'Error'), (19, 'Hit by pitch'), (20, 'Fielder choice'), (21, 'Catcher interference')], default=1)),
                ('batter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
            ],
        ),
        migrations.CreateModel(
            name='DefensePitchByPitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_count', models.IntegerField()),
                ('ball_count', models.IntegerField()),
                ('strike_count', models.IntegerField()),
                ('outcome', models.IntegerField(blank=True, choices=[(1, 'Strikeout Looking'), (2, 'Strikeout Swinging'), (3, 'Groundout'), (4, 'Pop/Flyout'), (5, 'Sacrifice Fly'), (6, 'Sacrifice Bunt'), (7, 'Infield Fly'), (8, 'Dropped 3rd strike'), (9, 'Double Play'), (10, 'Triple Play'), (11, 'Walk'), (12, 'Intentional Walk'), (13, 'Single'), (14, 'Double'), (15, 'Triple'), (16, 'Homerun'), (17, 'Inside park Homerun'), (18, 'Error'), (19, 'Hit by pitch'), (20, 'Fielder choice'), (21, 'Catcher interference')], default=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('pitcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
        ),
    ]
