# Generated by Django 3.2.20 on 2024-02-28 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20240113_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldergame',
            name='totalInGameOut',
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 16, 8, 41, 538137)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 16, 8, 41, 538137)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 16, 8, 41, 538137)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 16, 8, 41, 555351)),
        ),
    ]
