# Generated by Django 3.2.20 on 2024-03-07 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20240228_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='avatar',
            field=models.ImageField(blank=True, default='equipments/equipment.png', null=True, upload_to='equipments/'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='avatar_str',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 23, 37, 42, 678375)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 23, 37, 42, 680368)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 23, 37, 42, 678375)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 23, 37, 42, 682419)),
        ),
    ]
