# Generated by Django 3.2.20 on 2024-03-09 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20240307_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, 'Other'), (1, 'Bat'), (2, 'Ball'), (3, 'Glove')], default=-1, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.TextField(default='Noname'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 11, 47, 43, 412025)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 11, 47, 43, 414024)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 11, 47, 43, 412025)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 11, 47, 43, 416023)),
        ),
    ]
