# Generated by Django 3.2.20 on 2024-03-20 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20240321_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitchergame',
            old_name='oppSacrificeHit',
            new_name='oppSacrificeBunt',
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 1, 7, 11, 36258)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 1, 7, 11, 38260)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 1, 7, 11, 36258)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 1, 7, 11, 40264)),
        ),
    ]
