# Generated by Django 3.2.20 on 2024-03-23 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20240323_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitchergame',
            old_name='strikeout',
            new_name='oppStrikeout',
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 17, 52, 43, 78192)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 17, 52, 43, 78192)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 17, 52, 43, 78192)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 17, 52, 43, 78192)),
        ),
    ]
