# Generated by Django 3.2.20 on 2024-03-23 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20240323_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitchergame',
            name='catcherInterference',
        ),
        migrations.RemoveField(
            model_name='pitchergame',
            name='oppSacrificeBunt',
        ),
        migrations.RemoveField(
            model_name='pitchergame',
            name='oppSacrificeFly',
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 20, 41, 59, 22286)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 20, 41, 59, 22286)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 20, 41, 59, 22286)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 20, 41, 59, 22286)),
        ),
    ]
