# Generated by Django 3.2.20 on 2024-03-28 16:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20240328_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtBat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamScore', models.IntegerField(blank=True, default=0, null=True)),
                ('oppScore', models.IntegerField(blank=True, default=0, null=True)),
                ('out', models.IntegerField(blank=True, default=0, null=True)),
                ('inning', models.IntegerField(blank=True, default=1, null=True)),
                ('isTop', models.BooleanField(blank=True, default=True, null=True)),
                ('ball', models.IntegerField(blank=True, default=0, null=True)),
                ('strike', models.IntegerField(blank=True, default=0, null=True)),
                ('isOffense', models.IntegerField(blank=True, default=0, null=True)),
                ('isRunnerFirstDef', models.IntegerField(blank=True, null=True)),
                ('isRunnerSecondDef', models.IntegerField(blank=True, null=True)),
                ('isRunnerThirdDef', models.IntegerField(blank=True, null=True)),
                ('currentPlayer', models.IntegerField(blank=True, default=1, null=True)),
                ('oppCurPlayer', models.IntegerField(blank=True, default=1, null=True)),
                ('outcomeType', models.IntegerField(blank=True, choices=[(1, 'Strikeout Looking'), (2, 'Strikeout Swinging'), (3, 'Groundout'), (4, 'Pop/Flyout'), (5, 'Sacrifice Fly'), (6, 'Sacrifice Bunt'), (7, 'Infield Fly'), (8, 'Dropped 3rd strike'), (9, 'Ground into Double Play'), (10, 'Ground into Triple Play'), (11, 'Walk'), (12, 'Intentional Walk'), (13, 'Single'), (14, 'Double'), (15, 'Triple'), (16, 'Homerun'), (17, 'Inside park Homerun'), (18, 'Error'), (19, 'Hit by pitch'), (20, 'Fielder choice'), (21, 'Catcher interference'), (22, 'Fly into Double Play'), (23, 'Fly into Triple Play')], default=1)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='playergame',
            old_name='outfieldAssist',
            new_name='pitchStrike',
        ),
        migrations.RenameField(
            model_name='playergame',
            old_name='currentPos',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='playergame',
            name='pictchStrike',
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 28, 23, 14, 36, 749233)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 28, 23, 14, 36, 751232)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 28, 23, 14, 36, 750232)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 28, 23, 14, 36, 752232)),
        ),
        migrations.DeleteModel(
            name='PitchByPitch',
        ),
        migrations.AddField(
            model_name='atbat',
            name='currentPitcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_pitcher', to='api.playergame'),
        ),
        migrations.AddField(
            model_name='atbat',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game'),
        ),
        migrations.AddField(
            model_name='atbat',
            name='isRunnerFirstOff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner_first', to='api.playergame'),
        ),
        migrations.AddField(
            model_name='atbat',
            name='isRunnerSecondOff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner_second', to='api.playergame'),
        ),
        migrations.AddField(
            model_name='atbat',
            name='isRunnerThirdOff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner_third', to='api.playergame'),
        ),
    ]
