# Generated by Django 3.2.20 on 2024-03-28 19:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20240328_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atbat',
            name='currentPitcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_pitcher', to='api.playergame'),
        ),
        migrations.AlterField(
            model_name='atbat',
            name='isRunnerFirstOff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runner_first', to='api.playergame'),
        ),
        migrations.AlterField(
            model_name='atbat',
            name='isRunnerSecondOff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runner_second', to='api.playergame'),
        ),
        migrations.AlterField(
            model_name='atbat',
            name='isRunnerThirdOff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runner_third', to='api.playergame'),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 2, 27, 40, 182001)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 2, 27, 40, 185040)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 2, 27, 40, 182001)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 2, 27, 40, 186233)),
        ),
    ]
