# Generated by Django 3.2.20 on 2024-03-28 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20240329_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playergame',
            old_name='oppStrikeout',
            new_name='oppStrikeOut',
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 2, 49, 58, 843960)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 2, 49, 58, 845959)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 2, 49, 58, 843960)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 2, 49, 58, 846960)),
        ),
    ]
