# Generated by Django 3.2.20 on 2024-03-31 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20240330_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atbat',
            name='outcomeType',
            field=models.IntegerField(blank=True, choices=[(1, 'Strikeout Looking'), (2, 'Strikeout Swinging'), (3, 'Groundout'), (4, 'Pop/Flyout'), (5, 'Sacrifice Fly'), (6, 'Sacrifice Bunt'), (7, 'Infield Fly'), (8, 'Dropped 3rd strike'), (9, 'Ground into Double Play'), (10, 'Ground into Triple Play'), (11, 'Walk'), (12, 'Intentional Walk'), (13, 'Single'), (14, 'Double'), (15, 'Triple'), (16, 'Homerun'), (17, 'Inside park Homerun'), (18, 'Error'), (19, 'Hit by pitch'), (20, 'Fielder choice'), (21, 'Catcher interference'), (22, 'Fly into Double Play'), (23, 'Fly into Triple Play')], null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 10, 52, 33, 504909)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 10, 52, 33, 506908)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 10, 52, 33, 504909)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 10, 52, 33, 507908)),
        ),
    ]
