# Generated by Django 3.2.20 on 2024-03-31 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20240331_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atbat',
            name='currentPitcher',
        ),
        migrations.AddField(
            model_name='atbat',
            name='isLastState',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 15, 11, 35, 869459)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 15, 11, 35, 873030)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 15, 11, 35, 869854)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 15, 11, 35, 874026)),
        ),
    ]
