# Generated by Django 3.2.20 on 2024-04-18 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20240410_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Quited'), (0, 'Inactive'), (1, 'Active')], default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 21, 0, 55, 571757)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 21, 0, 55, 573757)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 21, 0, 55, 572756)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 21, 0, 55, 575757)),
        ),
    ]
