# Generated by Django 3.2.20 on 2024-04-22 05:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20240422_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpushtoken',
            name='user',
        ),
        migrations.AddField(
            model_name='userpushtoken',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.manager'),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 12, 53, 5, 80369)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 12, 53, 5, 82369)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 12, 53, 5, 81369)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 12, 53, 5, 83369)),
        ),
    ]
