# Generated by Django 3.2.20 on 2024-04-26 15:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20240422_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='atbat',
            name='pitcherResponseFirst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitch_first', to='api.playergame'),
        ),
        migrations.AddField(
            model_name='atbat',
            name='pitcherResponseSecond',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitch_second', to='api.playergame'),
        ),
        migrations.AddField(
            model_name='atbat',
            name='pitcherResponseThird',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitch_third', to='api.playergame'),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 42, 57, 572032)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 42, 57, 572032)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 42, 57, 572032)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 42, 57, 572032)),
        ),
    ]
