# Generated by Django 3.2.20 on 2024-04-30 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20240430_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='triple',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 22, 13, 26, 723071)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 22, 13, 26, 729834)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 22, 13, 26, 723071)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 22, 13, 26, 729834)),
        ),
    ]
