# Generated by Django 3.2.20 on 2024-05-09 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20240430_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 22, 55, 24, 879330)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 22, 55, 24, 894960)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 22, 55, 24, 894960)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
