# Generated by Django 3.2.20 on 2024-05-22 09:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20240520_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='team',
        ),
        migrations.AddField(
            model_name='notification',
            name='manager',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='api.manager'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 16, 3, 38, 916656)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 16, 3, 38, 916656)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 16, 3, 38, 916656)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 16, 3, 38, 916656)),
        ),
    ]
