# Generated by Django 3.2.20 on 2024-06-06 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20240603_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='players',
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 17, 25, 19, 835335)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 17, 25, 19, 835335)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 17, 25, 19, 850982)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 17, 25, 19, 835335)),
        ),
    ]
