# Generated by Django 3.2.20 on 2024-06-29 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20240606_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teamFund',
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 29, 14, 17, 58, 491581)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 29, 14, 17, 58, 491581)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 29, 14, 17, 58, 491581)),
        ),
        migrations.DeleteModel(
            name='PlayerPractice',
        ),
        migrations.DeleteModel(
            name='Practice',
        ),
    ]
