# Generated by Django 3.2.20 on 2024-07-15 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_auto_20240708_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='isUpdate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 12, 10, 29, 450622)),
        ),
        migrations.AlterField(
            model_name='game',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 12, 10, 29, 453620)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 12, 10, 29, 457618)),
        ),
    ]
