from django.urls import include, path
from .views import AcceptEventPlayerView, AcceptEventView, AcceptJoinRequestView, AtBatCreate, AtBatList, DenyEventPlayerView, DenyEventView, EquipmentUpdate, ErrorPageView, EventCreate, EventList, EventProfile, EventDelete, EventUpdate, GameCreate, GameList, GameProfile, GameUpdate, ImportPlayerAPIView, JoinTeamRequest, LeagueCreate, LeagueDelete, LeagueList, LeagueProfile, LeagueUpdate, ManagerCreate, ManagerList, ManagerProfile, ManagerUpdate, ObtainTokenPairWithView, PlayerAvatarUpdate, PlayerCreate, PlayerGameCreate, PlayerGameList, PlayerGameUpdate, PlayerList, PlayerProfile, PlayerStatList, PlayerUpdate, PushTokenList, SeedPushToken, SuccessPageView, TeamCreate, TeamListView, TeamProfile, TeamStatsView, TeamUpdate, TransactionCreate, TransactionList, TransactionProfile, TransactionUpdate, UpdatePushToken, UserCreate, UserLogin, TransactionDelete, EquipmentList, EquipmentCreate, EquipmentDelete, update_player
from rest_framework_simplejwt import views as jwt_views
from rest_framework.routers import DefaultRouter

# router = DefaultRouter()
# router.register(r'request_jointeam', JoinTeamRequest, basename='requestjointeam')
urlpatterns = [
     path('register/', UserCreate.as_view(), name='register-user'),
     path('login/', UserLogin.as_view(), name='user-login'),
     path('token/obtain/', ObtainTokenPairWithView.as_view(),
         name='token_create'),  # override sjwt stock token
     path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
     path("acceptjointeam/<pk>/",  AcceptJoinRequestView.as_view(), name="accept_jointeam"),
     path("acceptevent/<pk>/",  AcceptEventView.as_view(), name="accept_event"),
     path("denyevent/<pk>/",  DenyEventView.as_view(), name="deny_event"),
     path("accepteventplayer/<pk>/",  AcceptEventPlayerView.as_view(), name="accept_event_player"),
     path("denyeventplayer/<pk>/",  DenyEventPlayerView.as_view(), name="deny_event_player"),
     path("request_jointeam/",  JoinTeamRequest.as_view(), name="request_jointeam"),
     path('success/', SuccessPageView.as_view(), name='success_page'),
     path('error/', ErrorPageView.as_view(), name='error_page'),
     path('successeventpage/', SuccessPageView.as_view(), name='success_event_page'),
     path('denyeventpage/', ErrorPageView.as_view(), name='deny_event_page'),
     path('manager/profile/<int:pk>/',
         ManagerProfile.as_view(), name="manager_profile"),
     path('team/profile/<int:pk>/',
         TeamProfile.as_view(), name="team_profile"),
     path('teams/', TeamListView.as_view(), name='teams'),
     path('event/profile/<int:pk>/',
         EventProfile.as_view(), name="event_profile"),
     path('event/delete/<int:pk>/',
         EventDelete.as_view(), name="event_delete"),
     path('league/profile/<int:pk>/',
         LeagueProfile.as_view(), name="league_profile"),
     path('league/delete/<int:pk>/',
         LeagueDelete.as_view(), name="league_delete"),
     path('transaction/profile/<int:pk>/',
         TransactionProfile.as_view(), name="transaction_profile"),
    path('game/<int:pk>/',
         GameProfile.as_view(), name="game_profile"),
     path('transaction/delete/<int:pk>/',
         TransactionDelete.as_view(), name="transaction_delete"),
     path('transaction/delete/<int:pk>/',
         EquipmentDelete.as_view(), name="equipment_delete"),
     path('player/profile/<int:pk>/',
         PlayerProfile.as_view(), name="player_profile"),
     path('player/update-avatar/<int:playerid>/', PlayerAvatarUpdate.as_view(), name="player_update_avatar"),
     path('manager/create/', ManagerCreate.as_view(), name='manager_create'),
     path('managers/team/<int:teamid>/', ManagerList.as_view(), name='player-list'),
     path('team/create/', TeamCreate.as_view(), name='team_create'),
     path('event/create/', EventCreate.as_view(), name='event_create'),
     path('league/create/', LeagueCreate.as_view(), name='league_create'),
     path('game/create/', GameCreate.as_view(), name='game_create'),
     path('transaction/create/', TransactionCreate.as_view(), name='transaction_create'),
     path('equipment/create/', EquipmentCreate.as_view(), name='equipment_create'),
     path('playergame/create/', PlayerGameCreate.as_view(), name='playergame_create'),
     path('atbat/create/', AtBatCreate.as_view(), name='atbat_create'),
     path('player/create/', PlayerCreate.as_view(), name='team_create'),
     path('player/import/', ImportPlayerAPIView.as_view(), name='players_import'),
     path('players/team/<int:teamid>/', PlayerList.as_view(), name='player-list'),
     path('events/team/<int:teamid>/', EventList.as_view(), name='event-list'),
     path('leagues/team/<int:teamid>/', LeagueList.as_view(), name='league-list'),
     path('games/team/<int:teamid>/', GameList.as_view(), name='game-list'),
     path('transactions/team/<int:teamid>/', TransactionList.as_view(), name='transaction-list'),
     path('equipments/team/<int:teamid>/', EquipmentList.as_view(), name='equipment-list'),
     path('playergames/game/<int:gameid>/', PlayerGameList.as_view(), name='playergame-list'),
     path('atbats/game/<int:gameid>/', AtBatList.as_view(), name='atbat-list'),
     path('game/updates/<int:pk>/', GameUpdate.as_view(), name='game-update'),
     path('event/updates/<int:pk>/', EventUpdate.as_view(), name='event-update'),
     path('league/updates/<int:pk>/', LeagueUpdate.as_view(), name='event-update'),
     path('player/updates/<int:pk>/', PlayerUpdate.as_view(), name='player-update'),
     path('team/updates/<int:pk>/', TeamUpdate.as_view(), name='team-update'),
     path('manager/updates/<int:pk>/', ManagerUpdate.as_view(), name='manager-update'),
     path('transaction/updates/<int:pk>/', TransactionUpdate.as_view(), name='transaction-update'),
     path('equipment/updates/<int:pk>/', EquipmentUpdate.as_view(), name='equipment-update'),
     path('playergame/updates/<int:pk>/', PlayerGameUpdate.as_view(), name='playergame-update'),
     path('userpushtoken/seed/', SeedPushToken.as_view(), name='userpushtoken-seed'),
     path('userpushtoken/update/<int:manager_id>/', UpdatePushToken.as_view(), name='userpushtoken-update'),
     path('userpushtokens/<int:team_id>/', PushTokenList.as_view(), name='push-token-list'),
     path('playerstats/team/<int:teamid>/', PlayerStatList.as_view(), name='player-stats'),
     path('seedstats/', update_player, name='seed_stats'),
     path('teamstats/<int:team_id>/', TeamStatsView.as_view(), name='team_stats'),
    #  path('', include(router.urls)),
]
